# SPDX-FileCopyrightText: 2025 The geany contributors.
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
    - package-ecosystem: gomod
      directory: / # Location of package manifests
      schedule:
          interval: weekly

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
